theme: jekyll-theme-slate
name: Parth Khopkar
markdown: kramdown
# applies pretty for all
permalink: pretty

# overrides permalink for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title/
